### ISSUE TITLE
Flash of Unstyled Content

### ISSUE THREAD

**Issue by kerryboyko** [cleverfranke/cf-kyt-starter-universal-redux#31]
Howdy! Love the kyt! 

That said - there's a problem with it - one I hoped you'd solve (and which the NYT didn't)  When showing the page, there's a FOUC - flash of unstyled content.  That's really something that needs to be fixed in the NYT original kyt - but was hoping that you'd be able to do so as well.

**Comment by janhoogeveen** [comment]
That should really only happen when you're in development mode where honestly it really doesn't matter if there's a FOUC. Did you try running the kyt in a production build? 

```bash
yarn build && yarn start
```

**Comment by janhoogeveen** [comment]
Just verified this by making a filmstrip in Chrome Devtools. There is no FOUC visible when running in production mode.
