### ISSUE TITLE
Question: How to hook up the unit test to Redux

### ISSUE THREAD

**Issue by jcalfee** [cleverfranke/cf-kyt-starter-universal-redux#7]
I noticed that the unit tests are importing the non-redux connected components:

```javascript
//src/containers/Redux/index.js
export class ReduxContainer extends Component {
   ...
}

export default connect(mapStateToProps, mapDispatchToProps)(ReduxContainer);
```

```javascript
//src/containers/Redux/index.test.js
import { ReduxContainer } from './';
```

Can you recommend an architecture that would allow for the setup of the Redux server or client Provider in these unit tests?

So, something like this should be possible:

```javascript
//src/containers/Redux/index.test.js
import { Provider } from 'react-redux';
import ReduxContainer from './';

import configureStore from '../../redux/store';
const store = configureStore();

const handleIncrement = () => {};

it('should render the Redux container as a section element', () => {
  const wrapper = shallow(
    <Provider store={store}>
      <ReduxContainer shouldIncrement={handleIncrement} count={10} />
    </Provider>
  );
  expect(wrapper.is('section')).toBeTruthy();
});

```

Unfortunately I start getting errors like this: 

```javascript
    TypeError: _Object$keys(...).reduce is not a function
      
      at autoprefixes (../node_modules/react-dock/lib/Dock.js:40:31)
      at Object.<anonymous> (../node_modules/react-dock/lib/Dock.js:45:14)
      at Object.<anonymous> (../node_modules/react-dock/lib/index.js:9:13)
      at Object.<anonymous> (../node_modules/redux-devtools-dock-monitor/lib/DockMonitor.js:11:18)
```

The problem is not DockMonitor.  I'm running node v7.5 but it does not fully support es7 ..  Would you say the problem is in `kyt test`?  Perhaps `kyt test` needs to use babel-node to be fully compatible with the code.  Any ideas are appreciated..

**Comment by jcalfee** [comment]
Another clue, this unit test is failing:
```
 FAIL  containers/Addons/index.test.js
  ● should render the Addons container as a section element

    ReferenceError: __CLIENT__ is not defined
```
The `__CLIENT__` variable is setup in kyt.config.js's modifyWebpackConfig .. In kyt's default webpack they say they include the `babel-polyfill`.

**Comment by janhoogeveen** [comment]
Hey @jcalfee, good find!

So first up, our reasoning behind dropping Redux from tests (at least in the early phases) is the fact that we have a lot of trust that the Redux library itself is tested better than we ever could in our projects. We strongly rely on the quality of the Redux tests.

In terms of priority we think that testing components we create manually is the most important test that should be done. We need to know our components properly respond to prop changes. Where the props are coming from – this could be Redux or a parent, or in the tests a mockup prop – is really not that interesting.

It might make sense for us to think about testing our own reducers. E.g. does dispatching redux actions trigger the changes we expect in the store. 

I'll definitely be looking in the failing test, we've made some changes to the webpackConfig and probably need to copy some settings to the jest configuration as well.

**Comment by jcalfee** [comment]
Correct, I am in great need of testing the reducers and (in my case) the redux-saga code.

I'm still trying to understand the environment.  I added a reduce function in a component's render method directly trying to simulate the error I was getting above.  The unit test worked!  So I guess this means the component is babel ready but the imported code is not?

```javascript
// src/containers/Home/index.js
function Home() {
  Object.keys({}).reduce(r => {}, []); // it works!
  return (
    <section>
...
````

Do you know why I can use reduce on an array in the component but its imported code can not?  I suspect that the babel-polyfill is working in this project but it does not extend into modules like DockMonitor.

**Comment by janhoogeveen** [comment]
Quick update, we fixed the failing unit test. https://github.com/cleverfranke/cf-kyt-starter-universal-redux/tree/v1.3.3

It's not really related to the core question of this issue, but thought you might want to know anyway. 

I'm going to leave this issue open since maybe sometime in the future we'd like to add working tests for reducers, but it's very low priority. In the meantime if you find something that could help us improve the tests easily we'd love to see a PR.

Thanks again!

**Comment by janhoogeveen** [comment]
@jcalfee Is this something that helps you? http://redux.js.org/docs/recipes/WritingTests.html#writing-tests

**Comment by janhoogeveen** [comment]
@jcalfee We've made a PR in which we'll add examples testing reducers in the unit tests. We're not going to finish this very soon but you could take a look at what we're doing and use it in your own project already.

https://github.com/cleverfranke/cf-kyt-starter-universal-redux/pull/25

**Comment by jcalfee** [comment]
@markhaasjes fantastic thank you..
